# Generated by Django 5.0.4 on 2024-05-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total1',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('qty1', models.CharField(blank=True, max_length=10, null=True)),
                ('rate1', models.CharField(blank=True, max_length=10, null=True)),
                ('total1', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='home.invoice')),
            ],
        ),
    ]
