# Generated by Django 5.0.4 on 2024-05-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_invoice_product_remove_invoice_qty1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='invoice',
        ),
    ]
